'use client';

import { useEffect, useMemo, useState } from 'react';

interface RoomPageProps {
  params: {
    roomName: string;
  };
}

const DAILY_SUBDOMAIN = process.env.NEXT_PUBLIC_DAILY_SUBDOMAIN;

if (!DAILY_SUBDOMAIN) {
  throw new Error(
    'NEXT_PUBLIC_DAILY_SUBDOMAIN environment variable is required but not configured. ' +
    'Please set it to your Daily.co subdomain.'
  );
}

/**
 * Validates that roomName matches the expected pattern generated by the API.
 * Valid formats: room-{uuid} or room-{timestamp}-{randomstring}
 */
function isValidRoomName(roomName: string): boolean {
  // Match room-{uuid} format (e.g., room-550e8400-e29b-41d4-a716-446655440000)
  const uuidPattern = /^room-[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i;
  
  // Match room-{timestamp}-{randomstring} format (e.g., room-1234567890-abc123xy)
  const timestampPattern = /^room-\d+-[a-z0-9]+$/i;
  
  return uuidPattern.test(roomName) || timestampPattern.test(roomName);
}

function buildDailyRoomUrl(roomName: string): string {
  return `https://${DAILY_SUBDOMAIN}.daily.co/${encodeURIComponent(roomName)}`;
}

function detectMobileViewport(): boolean {
  if (typeof window === 'undefined') {
    return false;
  }

  return window.matchMedia('(max-width: 768px), (pointer: coarse)').matches;
}

export default function RoomPage({ params }: RoomPageProps) {
  const [isMobileViewport, setIsMobileViewport] = useState(false);
  const roomUrl = useMemo(() => buildDailyRoomUrl(params.roomName), [params.roomName]);
  const isValid = isValidRoomName(params.roomName);

  useEffect(() => {
    const updateViewportMode = () => {
      setIsMobileViewport(detectMobileViewport());
    };

    updateViewportMode();

    if (typeof window === 'undefined') {
      return;
    }

    const mediaQuery = window.matchMedia('(max-width: 768px), (pointer: coarse)');
    mediaQuery.addEventListener('change', updateViewportMode);
    window.addEventListener('resize', updateViewportMode);
    window.addEventListener('orientationchange', updateViewportMode);

    return () => {
      mediaQuery.removeEventListener('change', updateViewportMode);
      window.removeEventListener('resize', updateViewportMode);
      window.removeEventListener('orientationchange', updateViewportMode);
    };
  }, []);
  
  // Validate roomName against expected pattern
  if (!isValid) {
    return (
      <main
        style={{
          display: 'flex',
          flexDirection: 'column',
          alignItems: 'center',
          justifyContent: 'center',
          height: '100dvh',
          padding: '1rem',
          backgroundColor: '#000',
          color: '#fff',
          textAlign: 'center',
        }}
      >
        <h1 style={{ fontSize: '2rem', marginBottom: '1rem' }}>Invalid Room</h1>
        <p style={{ marginBottom: '1.5rem', maxWidth: '32rem' }}>
          The room identifier &ldquo;{params.roomName}&rdquo; is not valid. 
          Please check the URL and try again.
        </p>
        <a
          href="/dashboard"
          style={{
            padding: '0.75rem 1.5rem',
            backgroundColor: '#39FF14',
            color: '#000',
            borderRadius: '0.5rem',
            textDecoration: 'none',
            fontWeight: 'bold',
          }}
        >
          Go to Dashboard
        </a>
      </main>
    );
  }

  return (
    <main
      style={{
        position: 'relative',
        width: '100%',
        height: '100dvh',
        overflow: 'hidden',
        backgroundColor: '#000',
      }}
    >
      <iframe
        title={`Daily room ${params.roomName}`}
        src={roomUrl}
        allow="camera; microphone; fullscreen; speaker-selection; display-capture"
        allowFullScreen
        style={{
          position: 'absolute',
          top: 0,
          left: 0,
          width: '100%',
          height: '100dvh',
          border: 0,
          objectFit: isMobileViewport ? 'cover' : 'contain',
        }}
      />
    </main>
  );
}
